name: Java CI

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y -q update
        sudo apt-get -y -q install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: -PverboseTests=true check
    - name: codecov.io
      uses: codecov/codecov-action@v2.1.0
